/**
 * Compiler — converts the node graph into readable JavaScript.
 */
export class Compiler {
  constructor(state, registry) {
    this.state = state;
    this.registry = registry;
  }

  compile() {
    const nodes = this.state.get('nodes');
    const connections = this.state.get('connections');
    const lines = ['// Generated by NodeForge', ''];
    const compiled = new Set();
    const indent = (n) => '  '.repeat(n);

    const findSrc = (nodeId, portId) => {
      const c = connections.find(c => c.toNode === nodeId && c.toPort === portId);
      return c ? `node_${c.fromNode}` : null;
    };

    const nodeExpr = (nodeId) => `node_${nodeId}`;

    const compileNode = (nodeId, level) => {
      if (compiled.has(nodeId)) return '';
      compiled.add(nodeId);
      const nd = nodes.get(nodeId);
      if (!nd) return '';
      const def = this.registry.get(nd.type);
      if (!def) return '';
      let code = '';
      const il = indent(level);

      // Compile data source nodes first
      const inConns = connections.filter(c => c.toNode === nodeId && c.type !== 'exec');
      for (const c of inConns) {
        code += compileNode(c.fromNode, level);
      }

      switch (nd.type) {
        case 'data.number':
          code += `${il}const ${nodeExpr(nodeId)} = ${nd.data?.value ?? 0};\n`;
          break;
        case 'data.string':
          code += `${il}const ${nodeExpr(nodeId)} = "${nd.data?.value ?? ''}";\n`;
          break;
        case 'data.boolean':
          code += `${il}const ${nodeExpr(nodeId)} = ${nd.data?.value === 'true'};\n`;
          break;
        case 'data.print': {
          const src = findSrc(nodeId, 'value');
          code += `${il}console.log(${src || 'undefined'}); // Print\n`;
          break;
        }
        case 'data.set_variable': {
          const name = nd.data?.name || 'myVar';
          const src = findSrc(nodeId, 'value');
          code += `${il}let ${name} = ${src || 'undefined'};\n`;
          break;
        }
        case 'data.get_variable': {
          const name = nd.data?.name || 'myVar';
          code += `${il}const ${nodeExpr(nodeId)} = ${name};\n`;
          break;
        }
        case 'data.prompt_number': {
          const msg = JSON.stringify(nd.data?.message || 'Enter a number:');
          code += `${il}const ${nodeExpr(nodeId)} = Number(prompt(${msg})) || 0;\n`;
          break;
        }
        case 'math.add': {
          const a = findSrc(nodeId, 'a') || '0', b = findSrc(nodeId, 'b') || '0';
          code += `${il}const ${nodeExpr(nodeId)} = ${a} + ${b};\n`;
          break;
        }
        case 'math.subtract': {
          const a = findSrc(nodeId, 'a') || '0', b = findSrc(nodeId, 'b') || '0';
          code += `${il}const ${nodeExpr(nodeId)} = ${a} - ${b};\n`;
          break;
        }
        case 'math.multiply': {
          const a = findSrc(nodeId, 'a') || '0', b = findSrc(nodeId, 'b') || '0';
          code += `${il}const ${nodeExpr(nodeId)} = ${a} * ${b};\n`;
          break;
        }
        case 'math.divide': {
          const a = findSrc(nodeId, 'a') || '0', b = findSrc(nodeId, 'b') || '1';
          code += `${il}const ${nodeExpr(nodeId)} = ${a} / ${b};\n`;
          break;
        }
        case 'math.random': {
          const min = findSrc(nodeId, 'min') || '0', max = findSrc(nodeId, 'max') || '100';
          code += `${il}const ${nodeExpr(nodeId)} = Math.floor(Math.random() * (${max} - ${min} + 1)) + ${min};\n`;
          break;
        }
        case 'logic.if': {
          const src = findSrc(nodeId, 'condition');
          code += `${il}if (${src || 'false'}) {\n`;
          break;
        }
        case 'web.set_text': {
          const t = findSrc(nodeId, 'target') || '"?"';
          const v = findSrc(nodeId, 'text') || '""';
          code += `${il}document.querySelector(${t}).textContent = ${v};\n`;
          break;
        }
        case 'web.set_style': {
          const t = findSrc(nodeId, 'target') || '"?"';
          const v = findSrc(nodeId, 'value') || '""';
          const prop = nd.data?.property || 'color';
          code += `${il}document.querySelector(${t}).style.${prop} = ${v};\n`;
          break;
        }
        case 'web.create_element': {
          const tag = nd.data?.tag || 'div';
          const id = nd.data?.id || '';
          code += `${il}const ${nodeExpr(nodeId)} = document.createElement("${tag}");${id ? ` ${nodeExpr(nodeId)}.id = "${id}";` : ''}\n`;
          break;
        }
        case 'events.on_start':
          code += `${il}(function main() {\n`;
          break;
        case 'events.on_click': {
          const target = nd.data?.target || '#playground';
          code += `${il}document.querySelector("${target}").addEventListener("click", () => {\n`;
          break;
        }
        default:
          code += `${il}// ${def.name}\n`;
      }

      // Follow exec connections
      const outConns = connections.filter(c => c.fromNode === nodeId);
      const execConns = outConns.filter(c => c.type === 'exec');

      const childLevel = level + (def.outputs?.some(p => p.type === 'exec') ? 1 : 0);
      for (const c of execConns) {
        code += compileNode(c.toNode, childLevel);
      }

      if (nd.type === 'logic.if') code += `${il}}\n`;
      if (nd.type === 'events.on_start') code += `${il}})();\n`;
      if (nd.type === 'events.on_click') code += `${il}});\n`;

      return code;
    };

    // Find entry nodes
    let foundEntry = false;
    for (const [id, nd] of nodes) {
      const def = this.registry.get(nd.type);
      if (!def) continue;
      const hasExecIn = (def.inputs || []).some(p => p.type === 'exec');
      const hasExecOut = (def.outputs || []).some(p => p.type === 'exec');
      if (!hasExecIn && hasExecOut) {
        foundEntry = true;
        lines.push(compileNode(id, 0));
      }
    }

    if (!foundEntry) {
      lines.push('// No event nodes found.');
      lines.push('// Add an "On Start" node and connect it to see generated code.');
    }

    return lines.join('\n');
  }
}
